### ISSUE TITLE
link shorten does not work

### ISSUE THREAD

**Issue by Freakyfelix** [Tygs/0bin#100]
I don't get the link... its only working on creating it.

**Comment by trustmeimaloser** [comment]
Same here. 

When I click "Get Short URL" it stucks on " Loading Short Url"

**Comment by sametmax** [comment]
It means we reached the limit of Google API calls. We should make a sign to warn people.

**Comment by sametmax** [comment]
Alternative :  https://huit.re/a
```
$.post('https://huit.re/a', {'lsturl': 'https://news.ycombinator.com/item?id=19080742', "format": "json"}, function(data) {
  console.log(data)
})```

Works. We should switch to them.

**Comment by Mhowser** [comment]
Any update to this?

**Comment by jonaskohl** [comment]
AFAIK this won't be fixable, at least it would mean that 0bin would need to switch over to another URL shortener, as [Google's goo.gl shortener was shut down April 13, 2018](https://developers.googleblog.com/2018/03/transitioning-google-url-shortener.html).

**Comment by Mhowser** [comment]
It can't be its own URL shortener?

**Comment by cebaa** [comment]
@Mhowser 

> It can't be its own URL shortener?

No for 2 reasons:

- It will go against the promise of "All pastes are AES256 encrypted, we cannot know what you paste...", since shortening the URL will require the whole URL - so key included - to be sent to the same server.
- The main property of short URLs is to be, well, short. That also makes them much easier to guess and a target for getting the contents not intended for you by brute-forcing URLs.

**Comment by Mhowser** [comment]
I see. Would it be possible to shorten the key itself? Like using Unicode characters instead of just regular letters.

**Comment by sametmax** [comment]
Yes, but unfortunatly many software don't support unicode correctly. Many would would not accept copy/pasting the URL, display it incorrectly, or worse, truncate it. I'm pretty sure it would insta break most url auto linkers.

Try this in forms, and see what happens: http://ko.wikipedia.org/wiki/위키백과:대문

**Comment by Mhowser** [comment]
![Screenshot_20200717-091413](https://user-images.githubusercontent.com/24195572/87808085-0360e300-c80e-11ea-8211-f436f1fc12ad.png) my browser changes it to this URL when clicking that link, so it does work at least for me.

I also noticed that if you 'select link text' it keeps the Unicode intact versus 'copying link address'.

Here it's tested on discord chat
![Screenshot_2020-07-17-09-23-27](https://user-images.githubusercontent.com/24195572/87808976-7585f780-c80f-11ea-9be6-c803a54e6493.png)

![IMG_20200717_092851](https://user-images.githubusercontent.com/24195572/87809286-fba23e00-c80f-11ea-9b27-5593dfa4f058.jpg)

I believe the way Twitter handles the Unicode in the URL is a bug and should be reported to them.

**Comment by ksamuel** [comment]
A new version is incomming in the V2 branch, and will be put in prod soon.
This version remove the "short url" features. It's been broken since day one, because no service expose a free unlimited API for long.
Since we can't host it ourselves, we had to cut it out.
