### ISSUE TITLE
Being able to share a file like pdf

### ISSUE THREAD

**Issue by jadjay** [Tygs/0bin#102]
If we can share files, it's better than dropbox or other share files systems, you can't have crypted files sharing.

For exemple when selecting "Upload File" you could have a select box "as file / as text", then the file / text could be crypted...

**Comment by sametmax** [comment]
I'm not sure we want to host entire files. Or maybe limit it to smalls 
files, under a certain size, to avoir the service to be used as a mean 
of video or games sharing.

**Comment by jadjay** [comment]
Yes small files ! Pdf stuff

Le 5 février 2016 18:44:10 CET, sametmax <notifications@github.com> a écrit :
>I'm not sure we want to host entire files. Or maybe limit it to smalls 
>files, under a certain size, to avoir the service to be used as a mean 
>of video or games sharing.
>
>Le 05/02/2016 17:32, jadjay a écrit :
>>
>> If we can share files, it's better than dropbox or other share files 
>> systems, you can't have crypted files sharing
>>
>> For exemple when selecting "Upload File" you could have a select box 
>> "as file / as text", then the file / text could be crypted
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/sametmax/0bin/issues/102>.
>>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sametmax/0bin/issues/102#issuecomment-180463255

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jadjay** [comment]
Yes but you check for your server but if so else want it ... Who cares it's his server, he's responsible for that

**Comment by CorbanR** [comment]
I think this would be a great feature. Something with a configurable option, with relativity low default.

**Comment by jadjay** [comment]
Could you be able to implement that ? Is it really different than to manage only text ?

**Comment by Natim** [comment]
Today it already works with images so it should not be too complex. We could even consider loading the pdf with [pdf.js](https://mozilla.github.io/pdf.js/)

**Comment by jadjay** [comment]
Okay, I'm asking that because we want to be part of "C.H.A.T.O.N.S" http://framablog.org/2016/02/09/chatons-le-collectif-anti-gafam/

And we need a crypted way of sharing files for our future users.

**Comment by Natim** [comment]
@jadjay then you might want to have a look at [Kinto](https://github.com/Kinto/kinto) and [Kinto-attachment](https://github.com/Kinto/kinto-attachment) because 0bin is not a storage service and not meant to be one.

**Comment by jadjay** [comment]
Hey I didn't talk about "STORAGE" I talk about "SHARING" with links, urls and stuff

**Comment by Natim** [comment]
Yes I know :) But as soon as you speak about sharing files you need to store them somewhere.

**Comment by jadjay** [comment]
Okay Why in hell blocking an usage ? 
It's the first rule in GPL, whatever the version. It's what make a project free and/or open source.
I'm not able to do this (by now...), but it's F%*$G simple to fork your project, it's github purpose of living.

Storing files and what kind of files is the responsability of the server owner, not the dev, 

Your self censure is "beyond understand-ability".

I think I understand where you want to go, but honestly that "privacy software thought shit".

Don't take it personnaly, I tried to discuss on the fact that you want to block a software usage. My english is bad and if you think I insult you, I swear that's not my goal and I apologie by advance.

**Comment by jadjay** [comment]
If i can take a comparison, it's like the knife inventor is responsible for all the murders done with a knife...

**Comment by Natim** [comment]
> Why in hell blocking an usage ?

Who is blocking what

You propose a feature that we don't need ourself but that you need, so go for it, we will review your patches and merge them if they make sense and do not bloat the software.

We take the time to help here, so why would you be so aggressive?

If you do not want our help do not ask for it and fork the project, however if you want to be part of the community and help improve the software, behave yourself so that we can talk while feeling your support.

**Comment by Natim** [comment]
@jadjay if you want to talk a bit more about this feature, you can join me in irc://irc.freenode.net/#kinto and we could even talk in french about it.

**Comment by jadjay** [comment]
@Natim I'm on the chan

why would you be so aggressive?

   I don't meant to be...

**Comment by Natim** [comment]
To be back at the discussion here.

The work I did at the time starts here: https://github.com/sametmax/0bin/pull/17/files#diff-e0ebdcf67f34fa1ef600db07151a13efR427

If we add another if: ```if (current_file.type.indexOf('application/pdf') == 0)```

We could probably make it loads with [pdf.js](https://mozilla.github.io/pdf.js/) that's all I am saying :)

**Comment by Natim** [comment]
This was for the upload part, also for the loading part, the code is here: https://github.com/sametmax/0bin/pull/17/files#diff-e0ebdcf67f34fa1ef600db07151a13efR629

**Comment by jadjay** [comment]
Okay I'll have a look tonight
