### ISSUE TITLE
Error when trying to install on Windows 10

### ISSUE THREAD

**Issue by theAkito** [Tygs/0bin#111]
I get this error:
`Traceback (most recent call last):
  File "zerobin.py", line 4, in <module>
    from zerobin.cmd import main
  File "R:\Akito\Programs\Mini\sametmax-0bin-7da1615\zerobin\cmd.py", line 12, in <module>
    from sigtools.modifiers import annotate, autokwoargs
ModuleNotFoundError: No module named 'sigtools'`

When issueing this command:
`python zerobin.py --host 0.0.0.0 --port 80 --compressed-static`

In PowerShell (admin). I use the newest Python to date.

**Comment by ashok-arora** [comment]
Module 'sigtools' will have to downloaded additionally to make it work on windows.

**Comment by Akito13** [comment]
Thanks, I will try that out.

**Comment by louisabraham** [comment]
Hello, I get an issue because of the pwd module that is missing on windows...

**Comment by sametmax** [comment]
This is an issue from introduced with the merge from https://github.com/sametmax/0bin/pull/88/commits/bd7a37255176992e1d78c018e27d6aa99e5beec6.

I merged external PR without checking them properly, and they introduced a lot of bugs.

I should basically reverse everything up to 66fe5d4 and make it the sane master branch again. While I do that, just use 66fe5d4.

**Comment by ashok-arora** [comment]
@louisabraham pwd module is for UNIX-like systems. Windows uses winpwd.

**Comment by Suleman-Elahi** [comment]
Same problem here....
![image](https://user-images.githubusercontent.com/24384996/68643071-1bbd8700-0536-11ea-9b6b-bbd78206bd10.png)

**Comment by Akito13** [comment]
@Suleman-Elahi 
What does `python --version` say?

**Comment by Suleman-Elahi** [comment]
@Akito13 

```
C:\>python --version
Python 3.7.4

C:\>
```

**Comment by Akito13** [comment]
@Suleman-Elahi 
Well, you could try it with Python2 but as far as I have seen, the `pwd` error is very common, as many people are complaining about it in different areas. Syntax errors in Python usually indicate that one is using the wrong Python version.
Typical Python crap, I suppose. Those are the reasons I don't understand why Python is beloved by so many developers. Python is truly one of the worst languages that were ever popular.

**Comment by ksamuel** [comment]
A new version has been pushed in the V2 branch, supporting python 3 only. 
I'm thinking about deprecating privilege as well.
After that, it may work on windows.

**Comment by ksamuel** [comment]
We definitely removed sigtool and privilege in the last version. If somebody want to give it a try on windows, we will welcome your feedback.
