### ISSUE TITLE
FF get error while redirecting

### ISSUE THREAD

**Issue by JustTB** [Tygs/0bin#120]
If I use 0bin normally:
* put text in
* click submit
On the loading bar it shows "redirecting" but nothing happens. The console says:
`NS_ERROR_FILE_CORRUPTED`

I'm using ff on kubuntu, in chromium it works.

**Comment by sametmax** [comment]
Your firefox localstorage file is corrupted: https://stackoverflow.com/a/18878068

Le 29/01/2019 à 22:10, JustTB a écrit :
