### ISSUE TITLE
DigitalOcean Marketplace

### ISSUE THREAD

**Issue by mayailkour** [Tygs/0bin#123]
What do you think of making 0bin available on the [DigitalOcean marketplace](https://marketplace.digitalocean.com/)?

**Comment by sametmax** [comment]
On est anonyme, on va pas donner notre compte à DO.

Le 09/06/2019 à 17:42, mayailkour a écrit :

**Comment by sametmax** [comment]
Sorry, wrong language.

We want to remain anonymous.

Le 10/06/2019 à 20:00, Sam et Max a écrit :

**Comment by mayailkour** [comment]
Ah, I see.  😎
