### ISSUE TITLE
Flash is blocked in modern browsers such as Chrome

### ISSUE THREAD

**Issue by Xayaan** [Tygs/0bin#126]
Paging #70 - It's been 4 years. Flash is blocked in modern browsers such as Chrome and considered obsolete almost everywhere.

**Comment by Natim** [comment]
@Xayaan do you feel like you could file a PR to replace the flash plugin using the new HTML5 APIs ? https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by lukem512** [comment]
There is also [this](https://jsfiddle.net/jdhenckel/km7prgv4/3) snippet. Is this repo still maintained? 0bin is a great tool and I'd be happy to make the PR if so.

**Comment by ksamuel** [comment]
We finally replaced the flash clipboard by the HTML5 API. Sadly, this means the copy/paste works only for text, not for images.

The branch v2 has the changes, but we will put it in prod soon.
