### ISSUE TITLE
Wondering how to decrypt in Python

### ISSUE THREAD

**Issue by yazeed44** [Tygs/0bin#130]
Hello. 

I'm trying to work on a basic 0bin client, in which the user will enter a URL(s) and the client will decrypt them locally, but I'm having trouble with decrypting content with the key embedded in the url. Here is the process I'm doing:
- Extract key from url and base64 decode it
- Extract "ct" value requesting the URL, and try to decrypt ct with the key

The problem is that I'm getting gibberish results. I'm probably missing something but I don't know what is. For AES, I'm using PyAes with AES mode CTR. You can take a look at the code I wrote over here: 
https://github.com/yazeed44/0bin-client/blob/master/Main.py

Thanks

**Comment by ksamuel** [comment]
You can use SJCL.py: https://pypi.org/project/sjcl/
