### ISSUE TITLE
Request increasing 500 KB default limit.

### ISSUE THREAD

**Issue by a-raccoon** [Tygs/0bin#132]
Hello.  I would like to request that the 500 KB cipher text limit be increased to a more accommodating size, of say 5 MB.  There are dozens and dozens of 0bin paste sites, and everybody uses this default setting.  Sadly, this prohibits pasting any long lists that exceed roughly 300 KB of plain text, or about 6000 to 10,000 lines of source code.

I understand that anybody could configure for a larger default, but nobody does, and so the ecology of 0bin is very restrictive throughout the Internet as of today.  I believe a 10x increase would be within reason without incurring abuses.

Thanks.

**Comment by ksamuel** [comment]
I just ran some stats on the main instance, the average on 200k+ pastes is about 200ko in size, encrypted. 

500K ought to be enough for anybody :)

**Comment by a-raccoon** [comment]
That's cool.  I still can't paste my list of things in just 1 paste anymore, after just 12 months of growth.  It's your opinion that >500K is too abusable then?  How many "paste too large" failures do you get per day on the main instance?

**Comment by ksamuel** [comment]
We don't keep log on the server for obvious reasons.

The site has no protection, it's already very easy to post abitrary content to it: split your files, send it to 100000 pastes, get them back. People used to do that with gmail for a while. There is even a FUSE driver. Keeping the number low limit the interest of such attack.

But even without abuse, 200 000 pastes at 200ko is already 40Go. I want to keep hosting cheap, and like you said, people don't change the value, and they would end up with a nasty surprise after some time.

If you need a higher value, your best bet is to ask one people hosting 0bin to change the value, or to host it yourself.

Cheers
