### ISSUE TITLE
Remove sigtools from requirements

### ISSUE THREAD

**Issue by Glandos** [Tygs/0bin#133]
Hi, and thanks for taking the lead!

It seems that `sigtools` was introduced and then removed from the code. It can be removed from `requirements.txt` and `setup.cfg`.

**Comment by ksamuel** [comment]
Good catch, I missed that.

**Comment by ksamuel** [comment]
I'm going to remove requirements.txt completely. Setup.cfg does the job fine.

**Comment by ksamuel** [comment]
Done in V1.0.1
