### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by veronikazaglotova** [Tygs/0bin#137]
Pic strongly related. Some people refuse to open 0bin.net because they see that certificate is expired
![2020-11-14-185404_1365x653_scrot](https://user-images.githubusercontent.com/52463107/99147413-fadcc400-26aa-11eb-9b0b-b02aaaaae29b.png)

**Comment by veronikazaglotova** [comment]
Forgot to add:

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for 0bin.net expired on 
> 11/13/2020.
>  
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by veronikazaglotova** [comment]
Also, someone recommended to use a certbot. Not sure what it is but I assume that it updates certificates automatically.

**Comment by ksamuel** [comment]
Yes, we are experiencing problems with our host and they seem to also have affected our certbot run.

I triggered it manually, and we are not migrating to a new server.
