### ISSUE TITLE
Possibility to add bins by a JSON request

### ISSUE THREAD

**Issue by darkrecher** [Tygs/0bin#14]
Wouldn't that be cool if we could paste a bin via a JSON request ? I personnaly need that for a script that periodically logs information from a webgame.

The user puts directly the text to paste in the request, and the type of expiration. 0bin answers the URL where to get the bin pasted.

If you want to prevent flooding, you could forbid the bin pasted via JSON to have the expiration "Never".

**Comment by ksamuel** [comment]
Hello, new maintainer here.

Thanks to sjcl.py, it's now easy to make a client in python. But I'm still unsure I'd want an API on this. I'm afraid it will open the door to bots and spammers, and we don't have the man power for that.

Then you have to code the API, document it, and maintain it. API are not like backend code, you break all the clients if you change it.

Bottom line, I'm -1 on this at the moment. But I'm open to discuss it again it the future.
