### ISSUE TITLE
How could I disable console logging?

### ISSUE THREAD

**Issue by luqaska** [Tygs/0bin#148]
That

**Comment by ksamuel** [comment]
To my knowledge, there is no logging by 0bin. What are you talking about ?

**Comment by luqaska** [comment]
I was reffering to the console log

**Comment by ksamuel** [comment]
There is no switch in zerobin to do so. Since you probably don't want to edit the code, your best bet is to redirect the output to /dev/null.

**Comment by luqaska** [comment]
It works! Thank you!
