### ISSUE TITLE
0bin.net parked

### ISSUE THREAD

**Issue by Osrepnay** [Tygs/0bin#149]
https://0bin.net is now a parked domain on namecheap, maybe it expired? My pastes are inaccessible now.

**Comment by ksamuel** [comment]
Yep, our credit was not high enough just before renewal and warnings went an old email nobody checked. Luckily, the domain name ended up in a grace period, and since you warned us quickly, we were able to reactivate it.

Thank you for saving our ass :)

Now let's wait for the DNS cache to flush.
