### ISSUE TITLE
0bin.net - Down?

### ISSUE THREAD

**Issue by DistantThunder** [Tygs/0bin#151]
The official demo site is down it seems, and not just for me:

* https://www.saashub.com/0bin-net-status

**Comment by Glandos** [comment]
```
   Domain Name: 0BIN.NET
   Registry Domain ID: 1715624767_DOMAIN_NET-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2022-06-02T23:00:02Z
   Creation Date: 2012-04-24T08:37:20Z
   Registry Expiry Date: 2023-04-24T08:37:20Z
```
It seems that it was renewed recently. But, maybe not by the original owners.

**Comment by megapro17** [comment]
add this to `"C:\Windows\System32\drivers\etc\hosts"`
`193.37.215.102 0bin.net`

**Comment by ksamuel** [comment]
Someone posted child porn on 0bin, and our domain name has been suspended. 

Luckily, the report included the full URL, included the hash, so we could identify the content, confirm that it was indeed CSAM, and remove the content.

We have requested the domain to be restored, which can take some time.

Usually we get direct emails for this kind of report, so I was surprised that they decided to work around us. More surprising is that they didn't contact our hosting this time, but our domain name provider. That's a first, getting our domain name cut off.

But all in all, it's the life of an encrypted pastebin as usual.

**Comment by ksamuel** [comment]
0bin.net is back online

**Comment by DistantThunder** [comment]
Thank you!
