### ISSUE TITLE
Can't disable `Never expire` option

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [Tygs/0bin#152]
I've skimmed trough the issues but I don't seem to find anything related.

Is there a way to disable the `Never expire` option?

Thanks in advance.

**Comment by ksamuel** [comment]
The expiring options are not configurable.

We are thinking about moving from a python configuration file to a toml one, and change a bit how conf is done in general. Being able to change the expiring options is probably our number one request (well, number 2 if you count publish an up to date doc).

So I'll close the ticket, but we are not closing the door to this.
