### ISSUE TITLE
Website unreachable

### ISSUE THREAD

**Issue by PeGaSuS-Coder** [Tygs/0bin#153]
When trying to access [0bin.net](https://0bin.net), we are presented with a `DNS_PROBE_FINISHED_NXDOMAIN` error.

Screenshot below:

![0bin net no_dns](https://user-images.githubusercontent.com/25697531/172063174-493e5772-6635-425e-972d-11f4e3c6c469.png)

**Comment by PeGaSuS-Coder** [comment]
Duplicate of #151

**Comment by ksamuel** [comment]
0bin.net is back online
