### ISSUE TITLE
Make the url shortener provider pluggable

### ISSUE THREAD

**Issue by sametmax** [Tygs/0bin#25]
Google url shortener has been mention has a better alternative with https hosted site. But is.id is a more neutral provider.

Been able to use both should be possible but setting it in the configuration file.

**Comment by v6** [comment]
// , Maybe there could be some sort of failover mode? 

Reminds me of #80.

**Comment by timss** [comment]
In the event that you're hosting 0bin yourself, having a native URL shortener on that domain would be preferably in certain scenarios. Maybe it could come in the form of an additional URL rewrite/route?

**Comment by sametmax** [comment]
That would defeat the entire purpose or 0bin as the server would need to 
hold the decryption key to redirect from the short url to the full url.

**Comment by timss** [comment]
Good point, hadn't thought about that. Please excuse my short sightedness.

**Comment by ksamuel** [comment]
The short url feature has been removed in V2, so I'm closing this.
