### ISSUE TITLE
Add a download button

### ISSUE THREAD

**Issue by ghost** [Tygs/0bin#47]
It will be good idea to implement a function to download the current paste and other to download all the pastes that are in the LocalStorage. Regards.

**Comment by davidak** [comment]
i also would like to have a download button.

**Comment by Natim** [comment]
For the current paste we can do it with a data:url on a href and we can even choose the name with the download attribute.

See https://github.com/spiral-project/formbuilder/blob/2002aaad0b91cc10e910cc8a4732ed35a3a25e77/src/js/components/FormEditor/FormHeader.js#L37 as an example.

For the multiple paste download, I don't think it is a feature we really need. (I would rather click on download on each)

But if we really want it, we can do an async.map on all the URL and build some sort of tar on client side, then build the data:url.

**Comment by Natim** [comment]
See https://gist.github.com/kig/408333 for tar on client side.

**Comment by juanito003** [comment]
At least it would be great to have the download button for the current url. In the current state it is not useable for a newbie. Imagine I sent a file to my little sister, I would have to explain to her to copy paste all the funny caracters and save them in a file with the correct extension. Now imagine I sent her a pdf or a sound file and she opens the link on her smartphone! How would she be able to save it properly?

**Comment by Natim** [comment]
@juanito003 Yes please feel free to start a PR I will help you.

**Comment by juanito003** [comment]
Sure. But let me first learn Python 3.

**Comment by sametmax** [comment]
@juanito003 : I like the "download this paste" feature, and would welcome a PR. Please insert the dl link after the " Copy paste | Get short url | Email this" links.

However, how do you plan on choosing the file name automatically ?

Indeed, 0bin does not target file sharing right now. You are not supposed to upload mp3 or pdf, although it may now work for some small files. But it's more of a side effect, as the UI is terrible at this.

The idea that we could make it a project allowing sharing file is interesting, but should be debated and in another ticket.

**Comment by ksamuel** [comment]
Done in V1.0.0
