### ISSUE TITLE
Non-root path support with web servers

### ISSUE THREAD

**Issue by ghost** [Tygs/0bin#52]
I am curious if there is a way to allow 0bin be run behind a web server at a non-root path, e.g.:  http://example.com/path/to/0bin

I've been toying with Apache with mod_proxy and mod_wsgi, and I keep getting errors with wanting to load resources from '/' (like /static or /create) when the server path is not at '/' but at some other location.

**Comment by omyno** [comment]
@pjz Did you ever find a solution for this?

**Comment by pjz** [comment]
Nope. I eventually gave up and made a virtual host for it.

**Comment by sametmax** [comment]
It's about time I work into 0bin again to solve this issue and port it to Python 3. It seems I can't find a good WE to do it. I'm sorry, I'm a real procrastinator sometime.

**Comment by ksamuel** [comment]
Well, new maintainer for 0bin now, so the V2 branch is now python 3 only :)
