### ISSUE TITLE
Flash required?

### ISSUE THREAD

**Issue by Fastidious** [Tygs/0bin#70]
Can it be done without requiring Flash?

**Comment by Yamakaky** [comment]
https://zenorocha.github.io/clipboard.js/

**Comment by lenisko** [comment]
clipboard.js is good idea.

**Comment by sametmax** [comment]
We can switch from flash to HTML 5, but honestly if I have a bit of time to work on 0bin, this ticket will be very low on my list : not enough benefits.

**Comment by ksamuel** [comment]
Fixed in the v2 branch,  soon in prod.
