### ISSUE TITLE
Syntax highlighting kidding with a triple quote string + regexp

### ISSUE THREAD

**Issue by serge-kilimoff** [Tygs/0bin#77]
With this code : 

``` python
REGEXP_PYTHON_VERSION = re.compile(r"""
    major\s*=\s*(?P<major>\d+)\s*,\s*
    minor\s*=\s*(?P<minor>\d+)\s*,\s*
    micro\s*=\s*(?P<micro>\d+)\s*,\s*
    releaselevel\s*=\s*['"](?P<releaselevel>\w+)['"]\s*,\s*
    serial\s*=\s*(?P<serial>\d+)
""", re.VERBOSE)
```

![screenshot](https://cloud.githubusercontent.com/assets/6053927/8135858/5ca1cffa-113a-11e5-98d9-03333d1aa741.jpeg)

**Comment by ksamuel** [comment]
The syntax detection algo is a abandoned google project. We keep it because it works on most code without having to tell which language it is, but it has some flaws. 

I think it's acceptable that sometimes a file don't work perfectly, given the convenience of not having to manually set the mode.
