### ISSUE TITLE
Get short url not working

### ISSUE THREAD

**Issue by mmikeww** [Tygs/0bin#80]
When I click the button, the link changes to "Loading short url" but nothing happens on any of the 3 major browsers. Am i doing something wrong?

**Comment by v6** [comment]
// , I have the same problem.

**Comment by sametmax** [comment]
We are using an Google API for shorlinks, and we reached the rate limit,
that's all. We should disable the link when the rate limit is reached.

**Comment by v6** [comment]
// , Donation time, I guess.

**Comment by Natim** [comment]
It remains me of https://github.com/sametmax/0bin/issues/25

**Comment by ksamuel** [comment]
The feature has been removed from 0bin. We cannot host short urls, and using a 3rd party service always lead to the API being shut down or being expensive in the long run.
