### ISSUE TITLE
save burn after read expiration, is it a bug or a feature ?

### ISSUE THREAD

**Issue by nicoxxl** [Tygs/0bin#81]
At lines 185-186, from paste.py :

``` python
            expiration = self.expiration + '#%s' % datetime.now()  # TODO: use UTC dates
            expiration = self.expiration 
```

**Comment by sametmax** [comment]
That's definitely a bug.

**Comment by rugk** [comment]
https://github.com/sametmax/0bin/issues/91 was merged, so it can be closed, can't it?

@Shir0kamii FYI: You can [let issues automatically close when a PR is merged](https://help.github.com/articles/closing-issues-via-commit-messages/).
