### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by treyhunner** [Tygs/0bin#82]
CloudFlare offers free SNI SSL.  This is really easy if you're on Heroku or a similar host that allows free HTTPS access.

**Comment by sametmax** [comment]
We will probably go with letsencrypt.org/ when it's live.

**Comment by p2004a** [comment]
letsencrypt is live :)

**Comment by BoboTiG** [comment]
:+1:

**Comment by ksamuel** [comment]
Indeed.

**Comment by rugk** [comment]
It seems it now uses HTTPS: https://0bin.net/

But the [config](https://www.ssllabs.com/ssltest/analyze.html?d=0bin.net) is improvable. 
I also created a HTTPS Everywhere ruleset: https://github.com/EFForg/https-everywhere/pull/4088

**Comment by kelek-** [comment]
I don't see a way to actually running it via HTTPS in the config file. Could somebody enlighten me please? :)

**Comment by sametmax** [comment]
HTTPS is not backed in into the zerobin server, only supported by the code. If you want HTTPS, you need to setup zerobin be served through a proxy such nginx, configured to use HTTPS.

**Comment by kelek-** [comment]
Thanks for your quick answer, I thought SSL would be implemented into the code itself.
Whatsoever, is there somewhere a quick guide how to setup nginx to use it with zerobin via SSL?

**Comment by ksamuel** [comment]
Use the regular nginx setup we have in a documentation, and from there
follow any tutorial on how to add SSL to nginx. It's not specific to
zerobin and will work.

**Comment by kamkudla** [comment]
Looks like the certificate has expired April 8th:
```
openssl s_client -showcerts -connect 0bin.net:443
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X1
verify return:1
depth=0 CN = 0bin.net
verify error:num=10:certificate has expired
notAfter=Apr  8 21:26:00 2016 GMT
verify return:1
depth=0 CN = 0bin.net
notAfter=Apr  8 21:26:00 2016 GMT
verify return:1
...    
    Start Time: 1460504108
    Timeout   : 300 (sec)
    Verify return code: 10 (certificate has expired)
---
```

**Comment by rugk** [comment]
> Whatsoever, is there somewhere a quick guide how to setup nginx to use it with zerobin via SSL?

You can follow the instructions [from Etherpad](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#nginx). But obviously you have to adjust them a bit.
