### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by treyhunner** [Tygs/0bin#83]
Is this project free software?  What license is the code under?

**Comment by v6** [comment]
// , https://www.zerobin.net/tos.html

**Comment by SEAPUNK** [comment]
@v6 This has nothing to do with the software license.

**Comment by SEAPUNK** [comment]
Also, because there is no LICENSE file, the project automatically defaults to this:

http://choosealicense.com/licenses/no-license/

**Comment by sametmax** [comment]
As stated within the README file :

> It's an Python implementation of the zerobin project under the WTF licence. It's easy to inst:l even if you know nothing about Python.

But yeah, having a LICENCE file would be nice.

**Comment by rugk** [comment]
:+1: for a license file.

In GitHub this is very [easy to add](https://help.github.com/articles/open-source-licensing/).

**Comment by ksamuel** [comment]
This has been fixed in the V2 branch, which we will merge with master soon.
