### ISSUE TITLE
Is cli compatible with original ZeroBin?

### ISSUE THREAD

**Issue by marsjaninzmarsa** [Tygs/0bin#84]
If it is, you should explicite wrote it in FAQ, I think. If not, why not?

**Comment by sametmax** [comment]
We didn't code cli, it's an external contribution, so I can't answer reliably the question, but I doubt it's compatible as we didn't attempt to have the same file format as zerobin. Our original goal has never been to have compatible implementation anyway. If this is important to you, you can try to get in touch with sebsauvage (the author of zerobin), et work with in on an official specification of these things. In that case, we may implement it. Alhough I'm not sure I see the value of it.

**Comment by marsjaninzmarsa** [comment]
I just see value of cli client for ZeroBin, I found this project and I like Python + Node approach more than bash + Rhyno/V8 approach, that's it.

**Comment by marsjaninzmarsa** [comment]
Just crosscompatible API for remote posting and getting content should be great (you are still using SJCL, so client-side encryption should work the same way, right?).

I may end-up with PR-s, so be warned! :stuck_out_tongue_winking_eye:

**Comment by sametmax** [comment]
I'm actually thinking of getting rid of the node part and rewrite that in Python. Their is not API for remote posting on either these projects except the HTTP POST. But if you do make a PR, I promise I will spend time considering it.

**Comment by ip1981** [comment]
Hi :-) FYI https://github.com/zalora/zerobin

**Comment by sametmax** [comment]
oh :)

**Comment by ksamuel** [comment]
The JS tool has been removed. Maybe in the future, we will add a Python equivalent, using sjcl.py.
